title = 'Simplex'
enableRobotsTXT = true
defaultContentLanguage = 'pt'

themesdir = 'themes'
theme = 'rusty-typewriter'

[params]
dateFormat = '02 de Jan de 2006'

[params.author]
name = 'Simplex'

[related]
includeNewer = true
[[related.indices]]
name = 'tags'
weight = 100

[params.rtwt]
searchPath = 'pesquisa'

[params.rtwt.side.home]
sidePaneSticky = false
taxonomies = ['tags']
countTaxonomy = 5

[params.rtwt.side.single]
sidePaneSticky = true
showDetails = true
showTableOfContents = true
showAttachments = true
showRelated = true
countRelated = 3

[languages.pt]
contentDir = 'content'
languageCode = 'pt-BR'
languageName = 'PortuguÃªs'

[[languages.pt.menus.main]]
name = 'Artigos'
pageRef = '/artigos'
weight = 1

# [[languages.pt.menus.main]]
# name = 'Sobre'
# pageRef = '/sobre.md'
# weight = 2

[[languages.pt.menus.main]]
name = 'GitHub'
url = 'https://github.com/osimplex'
weight = 3

# Image cache
[caches]
[caches.images]
dir = ':cacheDir/images'

# Search index
[outputFormats]
[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[mediaTypes]
[mediaTypes."application/json"]
suffixes = ["json"]

[outputs]
home = ["HTML", "RSS", "SearchIndex"]
