title = "Simplex"
enableRobotsTXT = true
defaultContentLanguage = "pt"

themesdir = "themes"
theme = "rusty-typewriter"

[params]
dateFormat = "2006-01-02"

[params.author]
name = "Simplex"

[markup]
[markup.highlight]
style = "github-dark"

[taxonomies]
palavra-chave = "palavras-chave"
ano = "ano"

[related]
includeNewer = true
[[related.indices]]
name = "palavras-chave"
weight = 100

[params.rtwt]
searchPath = "pesquisa"

[params.rtwt.side.home]
sidePaneSticky = false
taxonomies = ["palavras-chave", "ano"]
countTaxonomy = 5

[params.rtwt.side.single]
sidePaneSticky = true
showDetails = true
showTableOfContents = true
showAttachments = true
showRelated = true
countRelated = 3

[languages.pt]
contentDir = "content"
languageCode = "pt-BR"
languageName = "PortuguÃªs"

[languages.pt.pagination]
disableAliases = false
path = 'pagina'

[[languages.pt.menus.main]]
name = "Artigos"
pageRef = "/artigos"
weight = 1

[[languages.pt.menus.main]]
name = "Pesquisa"
pageRef = "/pesquisa"
weight = 2

[[languages.pt.menus.main]]
name = "RSS"
url = "/index.xml"
weight = 3

[[languages.pt.menus.main]]
name = "GitHub"
url = "https://github.com/osimplex"
weight = 4

[caches]
[caches.images]
dir = ":cacheDir/images"

[outputFormats]
[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[mediaTypes]
[mediaTypes."application/json"]
suffixes = ["json"]

[outputs]
home = ["html", "rss", "SearchIndex"]

[services]
[services.rss]
limit = 10
